const StaticComponentCoinList = [
  {
    symbol: "AVAX",
    id: "Avalanche",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "ETH",
    id: "Ethereum",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "USDT",
    id: "Tether",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },

  {
    symbol: "XRP",
    id: "Ripple",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },

  {
    symbol: "BTC",
    id: "Bitcoin",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "TLOS",
    id: "Telos",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "DOGE",
    id: "Dogecoin",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "XDB",
    id: "DigitalBits",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "SOL",
    id: "Solana",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "MM",
    id: "MetaMecha",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "TRB",
    id: "TELLOR",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "SEI",
    id: "Sei",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "ORDI",
    id: "Ordinals",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "FIL",
    id: "Filecoin",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "ARB",
    id: "Arbitrum",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
  {
    symbol: "GMT",
    id: "Stepin",
    price: "API Load..",
    high: "..%",
    marketValue: "API Load..",
  },
];
export default StaticComponentCoinList;
